# Generated by Django 5.0.6 on 2024-06-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('bio', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('photo', models.FileField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
