# Generated by Django 5.0.6 on 2024-06-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_employemodel_shopsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsmodel',
            name='bio',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AlterField(
            model_name='shopsmodel',
            name='city',
            field=models.CharField(default='default_value', max_length=50),
        ),
        migrations.AlterField(
            model_name='shopsmodel',
            name='name',
            field=models.CharField(default='default_value', max_length=20),
        ),
        migrations.AlterField(
            model_name='shopsmodel',
            name='phone',
            field=models.IntegerField(default='default_value', max_length=10),
        ),
        migrations.AlterField(
            model_name='shopsmodel',
            name='photo',
            field=models.FileField(default='default_value', upload_to=''),
        ),
    ]
