# Generated by Django 5.0.6 on 2024-06-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_shopsmodel_bio_alter_shopsmodel_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsmodel',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
    ]
