# Generated by Django 5.0.6 on 2024-06-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_shopsmodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsmodel',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
