# Generated by Django 5.0.6 on 2024-06-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_photo_shopsmodel_photo1_shopsmodel_photo2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsmodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='shopsmodel',
            name='photo1',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='shopsmodel',
            name='photo2',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='shopsmodel',
            name='photo3',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
