# Generated by Django 5.0.6 on 2024-06-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_shopsmodel_email_alter_shopsmodel_photo1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsmodel',
            name='photo1',
            field=models.ImageField(default='default_image.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='shopsmodel',
            name='photo2',
            field=models.ImageField(default='default_image.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='shopsmodel',
            name='photo3',
            field=models.ImageField(default='default_image.jpg', upload_to='images/'),
        ),
    ]
