# Generated by Django 5.0.6 on 2024-06-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_shopsmodel_photo1_alter_shopsmodel_photo2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopsmodel',
            old_name='city',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='shopsmodel',
            name='photo1',
            field=models.ImageField(default='default_image.jpg', upload_to='shop_photos/'),
        ),
        migrations.AlterField(
            model_name='shopsmodel',
            name='photo2',
            field=models.ImageField(default='default_image.jpg', upload_to='shop_photos/'),
        ),
        migrations.AlterField(
            model_name='shopsmodel',
            name='photo3',
            field=models.ImageField(default='default_image.jpg', upload_to='shop_photos/'),
        ),
    ]
