# Generated by Django 5.0.6 on 2024-06-30 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_city_shopsmodel_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='offermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('discri', models.CharField(max_length=100)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.shopsmodel')),
            ],
        ),
    ]
