# Generated by Django 5.0.6 on 2024-06-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_offermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsmodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.DeleteModel(
            name='offermodel',
        ),
    ]
