# Generated by Django 5.0.6 on 2024-06-30 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_shopsmodel_email_delete_offermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='offermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shopsmodel')),
            ],
        ),
    ]
