# Generated by Django 5.0.6 on 2024-06-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_offermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offermodel',
            name='photo',
            field=models.ImageField(upload_to='offer_photos/'),
        ),
    ]
