# Generated by Django 5.0.6 on 2024-07-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_offermodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsmodel',
            name='photo1',
            field=models.ImageField(null=True, upload_to='shop_photos/'),
        ),
        migrations.AlterField(
            model_name='shopsmodel',
            name='photo2',
            field=models.ImageField(null=True, upload_to='shop_photos/'),
        ),
        migrations.AlterField(
            model_name='shopsmodel',
            name='photo3',
            field=models.ImageField(null=True, upload_to='shop_photos/'),
        ),
    ]
