# Generated by Django 5.0.6 on 2024-07-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_shopsmodel_is_active_shopsmodel_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopsmodel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='shopsmodel',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='shopsmodel',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='shopsmodel',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='shopsmodel',
            name='photo2',
            field=models.ImageField(default='shop_photos/DSC_0340.jpg', upload_to='shop_photos/'),
        ),
        migrations.AlterField(
            model_name='shopsmodel',
            name='photo3',
            field=models.ImageField(default='shop_photos/IMG_0881.jpg', upload_to='shop_photos/'),
        ),
    ]
