# Generated by Django 5.0.6 on 2024-07-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_shopsmodel_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsmodel',
            name='photo2',
            field=models.ImageField(default='shop_photos/default_image.jpg', upload_to='shop_photos/'),
        ),
        migrations.AlterField(
            model_name='shopsmodel',
            name='photo3',
            field=models.ImageField(default='shop_photos/default_image.jpg', upload_to='shop_photos/'),
        ),
    ]
