# Generated by Django 5.0.6 on 2024-07-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_shopsmodel_photo2_alter_shopsmodel_photo3'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsmodel',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopsmodel',
            name='subscription_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopsmodel',
            name='subscription_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
