# Generated by Django 5.0.6 on 2024-07-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_shopsmodel_is_subscribed_shopsmodel_subscription_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsmodel',
            name='locationlink',
            field=models.CharField(default='default_value', max_length=50),
        ),
    ]
